language: ruby
rvm:
- 2.3.1
install:
- bundle update html-pipeline
- bundle update --bundler
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  on:
    branch: master