# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hacking semantics"
email: "your-email@example.com"
description: #>- # this means to ignore newlines until "baseurl:"
  "A Blog about NLP, Computational Linguistics, Deep Learning, Cognitive Science, and AI."
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hackingsemantics.xyz" # the base hostname & protocol for your site, e.g. http://example.com
repository: "annargrs/blog"
destination: ./docs

author:
  name: "Anna Rogers"
  avatar: "/assets/images/aro.jpg"
#  bio: "computational linguistics, cognition, AI and NLP"
#  uri: "http://www.annargrs.github.io"
  twitter: "annargrs"
  linkedin: "annargrs"
  github: "annargrs"
#  vine: "doesn't matter"
  links:
    - label: "IT University of Copenhagen"
      icon: "fas fa-fw fa-university"
      url: "https://pure.itu.dk/da/persons/anna-rogers"
    - label: "Homepage"
      icon: "fas fa-fw fa-home"
      url: "http://annargrs.github.io/"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar ai"
      # ai-semantic-scholar, ai-orcid - see more at https://jpswalsh.github.io/academicons/
      url: "https://scholar.google.com/citations?user=5oCYOE0AAAAJ&hl=en"
    - label: "Semantic Scholar"
      icon: "ai ai-semantic-scholar ai"
      url: "https://www.semanticscholar.org/author/Anna-Rogers/145046059"
    - label: "ORCID"
      icon: "ai ai-orcid ai"
      url: "https://orcid.org/0000-0002-4845-4023"


#todo add a default 120-x120 image to be used in cards for imageless posts
#og_image: /assets/images/site-logo.png

twitter_username: "annargrs"
#github_username:  "annargrs"
#name: "Anna Rogers"
logo: "/assets/images/logo-3col.png"
# for the site icon, change head/custom.html

masthead_title: "Hacking Semantics"
# Build settings
markdown: kramdown
# related posts
lsi: true
#theme: minima
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
#  - jekyll-archives


# File reading
include:
  - _pages
  - _redirects
exclude:
  - .sass-cache
  - Gemfile
  - node_modules
  - vendor
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile

keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

#head_scripts:
#  - https://code.jquery.com/jquery-3.2.1.min.js



scholar:
  # more options: https://pages.lip6.fr/Pascal.Poizat/blog/posts/2016/02/01/jekyll-and-bibtex/
  style: _bibliography/apa_modified.csl
  sort_by: author, year
  order: ascending
  bibliography_template: bib
  use_raw_bibtex_entry: true # to enable {{...}} inside bibtex




# enabling auto-generation of subtitle links
kramdown:
    auto_ids: true

# utterances comments
repository: "annargrs/blog" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# enable search
search: true

## default YAML for all posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"


#  # _docs
#  - scope:
#      path: ""
#      type: docs
#    values:
#      sidebar:
#        nav: "docs"
#Archive settings
category_archive:
  type: liquid #jekyll-archives
  path: /categories/
tag_archive:
  type: liquid #jekyll-archives
  path: /tags/

# jekyll-archives config
#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layouts:
#    category: archive-taxonomy
#    tag: archive-taxonomy
#  permalinks:
#    category: /categories/:name/
#    tag: /tags/:name/

# Outputting
permalink: /:year/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# SEO and Analytics
#google_site_verification : "todo"
#bing_site_verification   : "todo"
analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: "UA-127096214-2"
environment: production # should work, if not check if env set to development