# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hacking semantics"
email: "your-email@example.com"
description: #>- # this means to ignore newlines until "baseurl:"
  "A blog about cool stuff including Natural Language Processing, Computational Linguistics, Deep Learning, Cognitive Science, and AI."
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
repository: "annargrs/blog"

author:
  name: "Anna Rogers"
  avatar: "/assets/images/aro.png"
  bio: "Thinking aloud: computational linguistics, cognition, AI and NLP"
#  location: "Bengaluru, India"
  uri: "http://www.cs.uml.edu/~arogers/"
  twitter: "annargrs"
  github: "annargrs"
#  medium: ".aravindiyer"
  linkedin: "annargrs"



#twitter_username: "annargrs"
#github_username:  "annargrs"
#name: "Anna Rogers"
#logo: "/assets/images/aro.png"

masthead_title: "Hacking Semantics"
# Build settings
markdown: kramdown
#theme: minima
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# enable search
search: true

## default YAML for all posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs"
#  # _docs
#  - scope:
#      path: ""
#      type: docs
#    values:
#      sidebar:
#        nav: "docs"
#Archive settings
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/